# Generated by Django 4.0.6 on 2022-07-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=124, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
